INSERT INTO PERSONS (FIRST_NAME,LAST_NAME,PERSON_NUMBER,EMAIL_ADDRESS)
VALUES ('Paul','Mill','36457364','paul.mill@yahoo.com');
INSERT INTO PERSONS (FIRST_NAME,LAST_NAME,PERSON_NUMBER,EMAIL_ADDRESS)
VALUES ('John','White','36457367','john.white@yahoo.com');
INSERT INTO PERSONS (FIRST_NAME,LAST_NAME,PERSON_NUMBER,EMAIL_ADDRESS)
VALUES ('Kevin','Black','56457364','kevin.black@mail.com');